apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::633628306346:role/UdacityFlaskDeployCBKubectlRole
      username: build   
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::633628306346:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-VDIKT8WZYAOV
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-04-18T21:58:16Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
        f:mapUsers: {}
    manager: eksctl.exe
    operation: Update
    time: "2021-04-18T21:58:16Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1511"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: d816664b-767c-4000-9956-533392b08903
